name: Gin REST API CI

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GO_VERSION: 1.14

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{GO_VERSION}}

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...
