name: Gin REST API CI

env:
  default-branch: main
  go-version: 1.14

on:
  push:
    branches:
      - $default-branch
      - ci
  pull_request:
    branches: 
      - $default-branch
      - ci
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: $go-version

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...
